### PR TITLE
fix: (#154) Limit random selectable rift themes and objectives

### LINKED ISSUE #154: [Bug]: Key from Creative Menu
### Discord username

CyberDay

### What happened?

Pulling key from creative menu spawns rift w/ processor blocks

### Reproduction Steps

pull key from creative menu

### Version

0.1.0 (MVP)

### Relevant log output

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by immortius**
This PR adds tags to control the valid rift themes and objectives when selecting randomly for an uninitialized (creative menu generated) key.

Closes #154

### CODE REVIEW

File: src/main/java/com/wanderersoftherift/wotr/datagen/ModRiftThemeTagsProvider.java [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+    // Get parameters from the `GatherDataEvent`s.
+    public ModRiftThemeTagsProvider(PackOutput output, CompletableFuture<HolderLookup.Provider> lookupProvider) {
+        // Second parameter is the registry key we are generating the tags for.
+        super(output, ModRiftThemes.RIFT_THEME_KEY, lookupProvider, WanderersOfTheRift.MODID);
+    }
+
+    @Override
+    protected void addTags(HolderLookup.Provider lookupProvider) {
+        tag(ModTags.RiftThemes.RANDOM_SELECTABLE).add(TagEntry.optionalElement(WanderersOfTheRift.id("cave")))
+                .add(TagEntry.optionalElement(WanderersOfTheRift.id("forest")));
```
Comment (Patrigan) [inline src/main/java/com/wanderersoftherift/wotr/datagen/ModRiftThemeTagsProvider.java:24]: Should probably contain the mushroom too.

**Review by Patrigan — CHANGES_REQUESTED** [review]

**Comment by Patrigan** [comment]
I feel both random selections are so different. Should those two be aligned and made consistent?

File: src/main/java/com/wanderersoftherift/wotr/datagen/ModRiftThemeTagsProvider.java (hunk 1 above)
Comment (immortius) [reply src/main/java/com/wanderersoftherift/wotr/datagen/ModRiftThemeTagsProvider.java:24]: What is the condition for a theme being included in the creative menu generated key? Maybe I should remove forest?

Comment (Patrigan) [reply src/main/java/com/wanderersoftherift/wotr/datagen/ModRiftThemeTagsProvider.java]: I mean, maybe the creative menu should always be processor theme? Might help the builders.

Other than that, no real condition, I would primarily split processor from the list. We have a nether theme now too, unsure if that should go in or not.

**Review by Patrigan — APPROVED** [review]
